### ISSUE TITLE
Nagios start error

### ISSUE THREAD

**Issue by ranjeetranjan** [sadsfae/ansible-nagios#11]
fatal: [hostname]: FAILED! => {"changed": true, "cmd": ["systemctl", "restart", "nagios.service"], "delta": "0:00:00.037135", "end": "2017-01-28 17:05:23.980575", "failed": true, "rc": 1, "start": "2017-01-28 17:05:23.943440", "stderr": "Job for nagios.service failed because the control process exited with error code. See \"systemctl status nagios.service\" and \"journalctl -xe\" for details.", "stdout": "", "stdout_lines": [], "warnings": []}

[root@li849-175 ansible-nagios]# journalctl -xe
Jan 28 17:05:23 li849-175.members.linode.com nagios[23581]: Nagios Core 4.0.8
Jan 28 17:05:23 li849-175.members.linode.com nagios[23581]: Copyright (c) 2009-present Nagios Core Development Team and Community Contributors
Jan 28 17:05:23 li849-175.members.linode.com nagios[23581]: Copyright (c) 1999-2009 Ethan Galstad
Jan 28 17:05:23 li849-175.members.linode.com nagios[23581]: Last Modified: 08-12-2014
Jan 28 17:05:23 li849-175.members.linode.com nagios[23581]: License: GPL
Jan 28 17:05:23 li849-175.members.linode.com nagios[23581]: Website: http://www.nagios.org
Jan 28 17:05:23 li849-175.members.linode.com nagios[23581]: Reading configuration data...
Jan 28 17:05:23 li849-175.members.linode.com nagios[23581]: Warning: use_embedded_perl_implicitly is deprecated and will be removed.
Jan 28 17:05:23 li849-175.members.linode.com nagios[23581]: Warning: enable_embedded_perl is deprecated and will be removed.
Jan 28 17:05:23 li849-175.members.linode.com nagios[23581]: Warning: p1_file is deprecated and will be removed.
Jan 28 17:05:23 li849-175.members.linode.com nagios[23581]: Warning: sleep_time is deprecated and will be removed.
Jan 28 17:05:23 li849-175.members.linode.com nagios[23581]: Warning: external_command_buffer_slots is deprecated and will be removed. All commands are always processed upon arriva
Jan 28 17:05:23 li849-175.members.linode.com nagios[23581]: Warning: command_check_interval is deprecated and will be removed. Commands are always handled on arrival
Jan 28 17:05:23 li849-175.members.linode.com nagios[23581]: Read main config file okay...
Jan 28 17:05:23 li849-175.members.linode.com nagios[23581]: Warning: Duplicate definition found for host 'hostname' (config file '/etc/nagios/conf.d/webservers.cfg', starting
Jan 28 17:05:23 li849-175.members.linode.com nagios[23581]: Error: Could not add object property in file '/etc/nagios/conf.d/webservers.cfg' on line 9.
Jan 28 17:05:23 li849-175.members.linode.com nagios[23581]: Error processing object config files!
Jan 28 17:05:23 li849-175.members.linode.com nagios[23581]: ***> One or more problems was encountered while processing the config files...
Jan 28 17:05:23 li849-175.members.linode.com nagios[23581]: Check your configuration file(s) to ensure that they contain valid
Jan 28 17:05:23 li849-175.members.linode.com nagios[23581]: directives and data defintions.  If you are upgrading from a previous
Jan 28 17:05:23 li849-175.members.linode.com nagios[23581]: version of Nagios, you should be aware that some variables/definitions
Jan 28 17:05:23 li849-175.members.linode.com nagios[23581]: may have been removed or modified in this version.  Make sure to read
Jan 28 17:05:23 li849-175.members.linode.com nagios[23581]: the HTML documentation regarding the config files, as well as the
Jan 28 17:05:23 li849-175.members.linode.com nagios[23581]: 'Whats New' section to find out what has changed.
Jan 28 17:05:23 li849-175.members.linode.com systemd[1]: nagios.service: control process exited, code=exited status=1
Jan 28 17:05:23 li849-175.members.linode.com systemd[1]: Failed to start Nagios Network Monitoring.
-- Subject: Unit nagios.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit nagios.service has failed.
-- 
-- The result is failed.
Jan 28 17:05:23 li849-175.members.linode.com systemd[1]: Unit nagios.service entered failed state.
Jan 28 17:05:23 li849-175.members.linode.com systemd[1]: nagios.service failed.

**Comment by sadsfae** [comment]
Hey @adsizzler can you post the contents of your ```hosts``` inventory file please?  More than likely you've got a host entered under more than one category, they should not belong to more than one type of check category the way that the playbook operates and is templated.

e.g.

```
[servers]
host-01

[webservers]
host-02
```

It's ok though, they all have similar checks depending on type.  For example the ```webservers``` group inherits all the normal ```servers``` checks plus HTTP.

**Comment by ranjeetranjan** [comment]
It solved now. Thanks for your response. But now i am getting 2 error
1) 255 is out of bounds
2) DISK CRITICAL - /dev/root is not accessible: No such file or directory

**Comment by sadsfae** [comment]
Ansible uses the following to determine your root disk name, and this is the first time I've seen it not choose the correct one. 

e.g.

https://github.com/sadsfae/ansible-nagios/blob/master/install/roles/nagios-client/templates/nrpe.cfg.j2#L205

```
{{ ansible_mounts[0]['device'] }}
```

What does your ```df -h``` output look like on your host?  What about ```ls /dev/mapper/*``` ?
Do you have python installed on the target system that is giving the error?

What does your ```/etc/nagios/nrpe.cfg``` have in it for what's generated in the check_root?

```
cat /etc/nagios/nrpe.cfg | grep check_root
```


```255 is out of bounds``` may be indicative of selinux blocking nagios plugin checks (this is common unfortunately), also try setting ```setenforce 0``` and seeing if that makes it go away when you re-run the playbook.

Also check if there is anything in ```/var/log/audit/audit.log```

```
cat /var/log/audit/audit.log | grep -i avc | audit2why
```
