### ISSUE TITLE
reloading the iptables service

### ISSUE THREAD

**Issue by dcr226** [sadsfae/ansible-nagios#13]
Restarting the iptables service can be dangerous if you're using conntrack. Reloading is much nicer I think..

--- a/install/roles/nagios-client/tasks/main.yml
+++ b/install/roles/nagios-client/tasks/main.yml
@@ -99,7 +99,7 @@
   register: iptables_needs_restart
 
 - name: Restart iptables-services for TCP/{{nrpe_tcp_port}} (iptables-services)
-  shell: systemctl restart iptables.service
+  shell: systemctl reload iptables.service
   ignore_errors: true
   when: iptables_needs_restart != 0 and firewalld_in_use.rc != 0 and firewalld_is_active.rc != 0

**Comment by sadsfae** [comment]
Thanks for the suggestion, I will change this.
