### ISSUE TITLE
connect to address <<myIP>> and port 22: No route to host

### ISSUE THREAD

**Issue by ranjeetranjan** [sadsfae/ansible-nagios#14]
@sadsfae 
I am getting error in my all the server even have proper hostname. 
connect to address 132.134.52.36 and port 22: No route to host

**Comment by ranjeetranjan** [comment]
@sadsfae Just to update when I stop firewalld I did not get this error. With rich rule I have allowed all port for my network but still getting this error.

       

>  ```
> rule family="ipv4" source address="192.168.128.0/17" accept
> 	rule family="ipv4" source address="192.168.128.0/17" service name="ssh" accept
> 	rule family="ipv4" source address="192.168.128.0/17" port port="5666" protocol="tcp" accept
> 
> 
> ```

**Comment by sadsfae** [comment]
hey @ranjeetranjan if it works with firewalld stopped it's most likely your firewalld ruleset.  Red Hat [seems to think](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux_OpenStack_Platform/5/html/Installation_and_Configuration_Guide/sect-Configure_Nagios.html) you also need UDP/5666 open as well (though on my system only TCP/5666 is needed).

Try:

```
firewall-cmd --zone=public --add-port=5666/udp --permanent
firewall-cmd --zone=public --add-port=5666/tcp --permanent
firewall-cmd --zone=public --add-port=22/tcp --permanent
firewall-cmd --reload
```

**Comment by sadsfae** [comment]
Closing this out, please try the above suggestions.  If that doesn't work you should try the Ansible ping command which will detect connectivity between Ansible and your hosts.

http://docs.ansible.com/ansible/latest/ping_module.html

```
ansible -u root -i hosts all -m ping
```
