### ISSUE TITLE
Support for Ubuntu and Debian clients?

### ISSUE THREAD

**Issue by kyle-cleverex** [sadsfae/ansible-nagios#15]
Hi. Will you be adding support for installing the Nagios client on Ubuntu and Debian systems?

**Comment by sadsfae** [comment]
hey @kyle-cleverex sorry I won't be adding support for non-RPM distributions (CentOS/RHEL/Fedora), it's just too much to maintain and I don't use Ubuntu or Debian anywhere at the moment.
