### ISSUE TITLE
AnsibleUndefinedVariable: 'dict object' has no attribute 'ansible_default_ipv4'"

### ISSUE THREAD

**Issue by ranjeetranjan** [sadsfae/ansible-nagios#17]
Hi,

I am facing one issue "AnsibleUndefinedVariable: 'dict object' has no attribute 'ansible_default_ipv4''

Here you go my host file.
```
[nagios]
103.225.77.2
[servers]

mysql-conversions-1 ansible_host=192.168.139.74


[webservers]

api-docs ansible_host=192.168.152.188
[elkservers]

[elasticsearch]
[switches]

[oobservers]

[idrac]

```

**Comment by sadsfae** [comment]
Hey @ranjeetranjan please remove the ```ansible_host=``` from each entry and use /etc/hosts entries instead if you don't have a FQDN for them.  That parameter is only used for devices that don't support SSH and Python libraries (switches, out-of-band interfaces, etc).

**Comment by ranjeetranjan** [comment]
@sadsfae I am little confuse. Lets assume I am on 192.168.139.74.

```
root@mysql-conversions-1 ~]# cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

```
Please let me know what I have to remove? Or are you asking me to remove from Nagios server. 

```
[root@nagios ansible-nagios]# cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
```

**Comment by sadsfae** [comment]
Hey @ranjeetranjan 

In your Ansible hosts inventory file, remove ```ansible_host=``` directive.

Only the following inventory group entries require this (as it's used for devices without Python like out-of-band servers, PDU's, switches etc).

Unless you're using any of the below groups you have to **remove** the ```ansible_host=``` line after the hostname.

```
[switches]
[oobservers]
[idrac]
[supermicro-6048r]
[supermicro-6018r]
[supermicro-1028r]
```

**Comment by ranjeetranjan** [comment]
@sadsfae SO you mean to say use like below? 

```
[servers]
192.168.139.74
```

**Comment by sadsfae** [comment]
@ranjeetranjan yes, but do you have a hostname you can use?  IP address may work too (I've actually never tested it).  Even an ```/etc/hosts``` entry should suffice.
