### ISSUE TITLE
Can not update servers.cfg

### ISSUE THREAD

**Issue by Novatec1** [sadsfae/ansible-nagios#57]
**Your System Details** 

* Ansible version (`rpm -qa | grep ansible`):
* ansible-2.9.15-1.el7.noarch
* Operating System: (`cat /etc/redhat-release`)
* CentOS Linux release 7.5.1804 (Core)

**Describe the bug**
failed: [localhost] (item=servers.cfg) => {"ansible_loop_var": "item", "changed": false, "item": "servers.cfg", "msg": "AnsibleUndefinedVariable: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'ansible_os_family'"}

**To Reproduce / What were you Doing?**

**Expected Behavior**

**Logs / Screenshots**
If applicable, add logs or screenshots to help explain your problem.

**Additional Details**
Add any other context or details about the problem here.

**Comment by sadsfae** [comment]
Hi @Novatec1 thanks for filing this, can you paste your Ansible inventory file please? 

Do you have your actual nagios host (and only your nagios host) listed under inventory group _[nagios]_?

```
[nagios]
host-01
```
What is under the `[servers]` group  in your Ansible inventory?

This my inventory that I just tested against two fresh CentOS7 VM's using `ansible-2.9.16` with no problems.

```
# where ansible will deploy it.
[nagios]
host-01

# use this for generic Linux or FreeBSD servers
[servers]
host-02
```

If you intend on running Ansible locally against the same host you'll need to use a different inventory file format like:

```
[nagios]
localhost ansible_connection=local
```

However I haven't really tested this as this repo/playbook is meant to be run from a host other than the one you are installing Nagios onto (desktop, laptop, jump host, etc) but I'd think it will work.

**Comment by sadsfae** [comment]
Closing this as it's over a year old.
