### ISSUE TITLE
fatal: [host-01]: UNREACHABLE!

### ISSUE THREAD

**Issue by erwinpalma** [sadsfae/ansible-nagios#60]
**Your System Details** 

* Ansible version: ansible 2.9.18
* Operating System: CentOS 8

**Describe the bug**

I tried to install this playground, using the reader me instruction but when I run the command `ansible-playbook -i hosts install/nagios.yml` I get the error; **fatal: [host-01]: UNREACHABLE!**

I have tried using 
```ini
[nagios]
host-01

[nagios]
demo

[nagios]
159.x.x.247
```

![image](https://user-images.githubusercontent.com/30660343/110123152-d410dd80-7dc0-11eb-97f3-bc3ea82fe33e.png)

**To Reproduce / What were you doing?**

```
git clone https://github.com/sadsfae/ansible-nagios
cd ansible-nagios
sed -i 's/host-01/159.x.x.247/' hosts
time ansible-playbook -i hosts install/nagios.yml
```

**Comment by sadsfae** [comment]
Hi @erwinpalma it looks like you cannot ssh in as root to the `159.x.x.247` system.  If you use another user other than root then you'll want to update this here as `ansible_system_user:` value.  For example AWS likes to use the `ec-user`

https://github.com/sadsfae/ansible-nagios/blob/master/install/group_vars/all.yml#L7 

Try ssh'ing to that host as normal without running the playbook, if you can do that then use the playbook.
